modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"

[[mods]]
modId = "unusual_prehistory"
version = "1.0"
logoFile = "unusual_prehistory.png"
authors = "Unusual Modding"
displayName = "Unusual Prehistory 2"
description = '''
A Mod that allows you to revive creatures from the ancient past!'''

[[dependencies.unusual_prehistory]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unusual_prehistory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21]"
ordering = "NONE"
side = "BOTH"
