modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL = "https://github.com/PlatypusOfHats/Unusual-Prehistory-2/issues"

[[mods]]
    modId = "unusualprehistory2"
    version = "1.0.0"
    logoFile = "logo.png"
    itemIcon = "minecraft:bone"
    configBackground = "minecraft:textures/block/dark_oak_planks.png"
    authors = "Unusual Modding"
    displayURL = "https://github.com/PlatypusOfHats/Unusual-Prehistory-2"
    displayName = "Unusual Prehistory 2"
    description = '''A sequel to the Unusual Prehistory mod.'''

[[dependencies.unusualprehistory2]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.unusualprehistory2]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.unusualprehistory2]]
    modId = "geckolib"
    mandatory = true
    versionRange="[4.2,)"
    ordering = "NONE"
    side = "BOTH"
