modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
modId = "unusual_prehistory"
version = "${file.jarVersion}"
logoFile = "unusual_prehistory.png"
authors = "Barl Incorporated"
displayName = "Unusual Prehistory 2"
description = '''Revive creatures from the ancient past!'''

[[dependencies.unusual_prehistory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.unusual_prehistory]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "AFTER"
side = "BOTH"